git init
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05805.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05805.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05808.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05808.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05809.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05809.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05811.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05811.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05812.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05812.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05814.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05814.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05816.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05816.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05820.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05820.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05823.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05823.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05824.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05824.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05825.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05825.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05826.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05826.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05827.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05827.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05828.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05828.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05829.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05829.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05830.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05830.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05831.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05831.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05832.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05832.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05833.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05833.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05836.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05836.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05838.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05838.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05839.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05839.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05840.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05840.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05841.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05841.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05842.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05842.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05843.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05843.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05844.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05844.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05845.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05845.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05846.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05846.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05847.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05847.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05848.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05848.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05849.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05849.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05850.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05850.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05851.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05851.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05852.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05852.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05853.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05853.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05854.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05854.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05855.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05855.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05856.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05856.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05857.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05857.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05858.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05858.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05859.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05859.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05861.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05861.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05865.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05865.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05866.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05866.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05867.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05867.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05868.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05868.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05869.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05869.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05870.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05870.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05871.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05871.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05872.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05872.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05873.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05873.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05874.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05874.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05875.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05875.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05876.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05876.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05877.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05877.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05878.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05878.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05879.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05879.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05880.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05880.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05881.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05881.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05882.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05882.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05883.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05883.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05884.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05884.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05885.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05885.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05886.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05886.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05887.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05887.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05888.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05888.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05889.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05889.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05890.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05890.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05892.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05892.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05893.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05893.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05894.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05894.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05895.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05895.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05896.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05896.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05897.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05897.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05898.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05898.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05899.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05899.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05900.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05900.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05901.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05901.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05902.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05902.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05903.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05903.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05904.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05904.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05906.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05906.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05907.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05907.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05908.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05908.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05909.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05909.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05910.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05910.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05911.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05911.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05912.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05912.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05913.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05913.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05914.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05914.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05915.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05915.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05916.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05916.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05917.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05917.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05918.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05918.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05919.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05919.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05920.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05920.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05921.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05921.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05922.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05922.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05923.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05923.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05924.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05924.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05925.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05925.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05926.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05926.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05928.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05928.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05929.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05929.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05930.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05930.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05931.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05931.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05932.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05932.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05933.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05933.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05934.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05934.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05935.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05935.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05936.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05936.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05937.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05937.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05938.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05938.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05939.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05939.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05940.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05940.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05941.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05941.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05942.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05942.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05943.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05943.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05944.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05944.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05945.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05945.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05946.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05946.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05947.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05947.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05948.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05948.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05949.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05949.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05950.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05950.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05951.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05951.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05952.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05952.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05953.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05953.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05954.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05954.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05955.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05955.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05956.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05956.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05957.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05957.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05958.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05958.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05959.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05959.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05960.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05960.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05961.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05961.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05962.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05962.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05963.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05963.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05966.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05966.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05967.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05967.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05968.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05968.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05969.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05969.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05970.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05970.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05971.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05971.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05972.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05972.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05973.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05973.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05974.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05974.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05975.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05975.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05976.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05976.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05977.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05977.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05978.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05978.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05979.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05979.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05980.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05980.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05981.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05981.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05982.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05982.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05983.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05983.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05984.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05984.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05985.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05985.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05986.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05986.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05987.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05987.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05988.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05988.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05989.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05989.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05990.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05990.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05991.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05991.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05992.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05992.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05993.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05993.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05994.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05994.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05995.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05995.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05996.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05996.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05997.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05997.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05998.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05998.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC05999.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC05999.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06000.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06000.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06001.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06001.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06002.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06002.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06003.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06003.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06004.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06004.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06005.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06005.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06006.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06006.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06007.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06007.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06008.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06008.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06009.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06009.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06010.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06010.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06011.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06011.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06012.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06012.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06013.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06013.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06014.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06014.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06015.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06015.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06016.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06016.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06017.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06017.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06018.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06018.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06019.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06019.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06020.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06020.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06021.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06021.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06022.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06022.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06023.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06023.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06024.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06024.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06025.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06025.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06026.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06026.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06027.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06027.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06028.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06028.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06029.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06029.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06030.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06030.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06031.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06031.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06032.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06032.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06033.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06033.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06034.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06034.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06035.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06035.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06036.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06036.JPG"
git commit -m "adding image"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\DSC06037.JPG"
git add "D:\Photos\github uploads\Adival-pre-wedding\Adival-pre-wedding\thumbnails\DSC06037.JPG"
git commit -m "adding files"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main
git add *
git commit -m "everything else"
git branch -M main
git remote add origin "https://github.com/FamilyWebsites/Adival-pre-wedding.git"
git push -u origin main